### ISSUE TITLE
Missing updates on earthcare track

### ISSUE THREAD

**Issue by d70-t** [orcestra-campaign/book#133]
It seems like the earthcare tracks are not updated on a daily basis. Probably we'd have to disable caching for that notebook.
If the notebook executes quickly, we might disable the cache generally for that notebook. If not, we might have to find a way of disabling it only in the CI.

**Comment by lkluft** [comment]
I think it executes "reasonably quick" 🤷‍♂️ And users might be confused if their local version is cached and the website not. So at the moment I would opt to disable caching this notebook

**Comment by lkluft** [comment]
This should be fixed with #141 (and #145 🙈)

I will close this tomorrow, after we confirmed one successful scheduled build tonight
