### ISSUE TITLE
Flight report for 11. Aug.: Be more precise about WALES status

### ISSUE THREAD

**Issue by mwlidar** [orcestra-campaign/book#160]
For the WALES status the comment says: "Some issues on HSRL"
This is a bit too general an may be misinterpreted. I suggest the following text:

One of the WALES lasers was not locked to the HSRL filter for about 20 Minutes at the begin of the flight. Since the other laser was locked, there is no loss of data for the Rayleigh-signal. No issues otherwise.

**Comment by bjorn-stevens** [comment]
Great .. thanks.  The old message was just a place holder :)

**Comment by mwlidar** [comment]
The comment is still the old in the latest version. And I can't find a pull request (open or closed) that does the changes.
