### ISSUE TITLE
Update or remove science page?

### ISSUE THREAD

**Issue by yu71ng** [orcestra-campaign/book#184]
What shall we do with https://orcestra-campaign.org/science.html?
Shall we improve it? Or leave it out completely?

I think, as it is now, things are missing...

**Comment by lkluft** [comment]
I would opt to remove it since we don't seem to have the bandwidth to maintain it. If someone actually wants to fill and maintain it at some point, we can bring it back.

**Comment by yu71ng** [comment]
If we are going to remove the science page, keeping `references` won't make much sense either, right?

**Comment by lkluft** [comment]
It would be empty right now, so I tend to agree 😉

**Comment by mckimb** [comment]
Hey, I would like to update the science page with an introduction to the science that motivates percusion. I have already written this. Can you reinstate the science page @lkluft @yu71ng?
