### ISSUE TITLE
Add an export txt file to the export functions

### ISSUE THREAD

**Issue by JuliaWindmiller1987** [orcestra-campaign/book#304]
Hi Tobi and Lukas, could one of you perhaps turn the txt file that Bjorn has produced into another export button? That would be great!

**Comment by JuliaWindmiller1987** [comment]
Sorry, referring to the code at the end of the https://orcestra-campaign.org/plans/HALO-20240831a.html

**Comment by lkluft** [comment]
Fixed with Tobi's new `FlightPlan` export functionality
