### ISSUE TITLE
Add EarthCARE tracks for Barbados

### ISSUE THREAD

**Issue by lkluft** [orcestra-campaign/book#309]
With the release of pyorcestra (`v0.0.18`](https://github.com/orcestra-campaign/pyorcestra/releases/tag/v0.0.18) the `SattrackLoader` now offers an argument to select the region-of-interest (CAPE_VERDE or BARBADOS). It would be nice to add the Barbados track forecast to the web page, too.

**Comment by bjorn-stevens** [comment]
Is this taken care of?  @JakobDeutloff
