### ISSUE TITLE
Add link to GitHub repo

### ISSUE THREAD

**Issue by tmieslinger** [orcestra-campaign/book#34]
In the upper right corner we could add a link to the GitHub repo of the book similar to the How-to-eurec4a book (possible by adding [those or similar lines](https://github.com/eurec4a/how_to_eurec4a/blob/master/how_to_eurec4a/_config.yml#L26C1-L30C35) in the respective ORCESTRA config file.

**Comment by tmieslinger** [comment]
Ups, it seems from a quick check that the info is already in the [`_config.yaml`](https://github.com/orcestra-campaign/book/blob/main/orcestra_book/_config.yml) files, but the buttons are not displayed on the rendered page. Anybody knows why?

**Comment by d70-t** [comment]
Apparently this is due to us setting `html_theme_options` in `_config.yml`, as introduced by #5, because eventually the options relevant for the repo-links end up in the `html_theme_options` sphinx configuration, but once we set `html_theme_options` manually, all the other options are disregarded.
