### ISSUE TITLE
Add FIR boundaries to the flight plans

### ISSUE THREAD

**Issue by JuliaWindmiller1987** [orcestra-campaign/book#350]
As we will have some flight information region (FIR) dependent restrictions when starting from Barbados, it would be great if we had the option to show the FIRs on the flight plan :)

**Comment by bjorn-stevens** [comment]
This seems like it is done?  At least I saw this on @hgloeckner plans

**Comment by hgloeckner** [comment]
Yes, but it's not part of pyorcestra yet.

**Comment by yoctoyotta1024** [comment]
Mine too! :')
