### ISSUE TITLE
Re-opening the science page

### ISSUE THREAD

**Issue by mckimb** [orcestra-campaign/book#364]
Hey, I would like to update the science page with an introduction to the science that motivates percusion. I have already written this. Can you reinstate the science page @lkluft @yu71ng?

_Originally posted by @mckimb in https://github.com/orcestra-campaign/book/issues/184#issuecomment-2331713081_

**Comment by d70-t** [comment]
Awesome 👏, I really hoped that there's some science associated with this field campaign!

**Comment by mckimb** [comment]
Do you know how I can open the science page again?

**Comment by lkluft** [comment]
The document itself is still there and also build. You just have to add it to the `_toc.yaml` again

**Comment by d70-t** [comment]
Probably you'd also need the references as well. Depending on the features required, you may want to undo parts or the entirety of #223.

**Comment by yu71ng** [comment]
Issued by #367
