### ISSUE TITLE
Sub-Campaign Logos on the front page

### ISSUE THREAD

**Issue by d70-t** [orcestra-campaign/book#42]
Now that we have all these nice Sub-Campaign Logos, I could imagine that we could have a gallery of all these logos on the front page, something which could look similar to [matplotlib examples](https://matplotlib.org/stable/gallery/index#lines-bars-and-markers) or the [seaborn gallery](https://seaborn.pydata.org/examples/index.html).

**Comment by yu71ng** [comment]
Yeah, I was thinking of something similar... But I was rather wondering, if it is possible to add the sub-logos in the Footer?

**Comment by d70-t** [comment]
We can also add the sub-logos into the footer (of every page?). This should be possible through adding a custom footer template in [the layout configuration](https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/layout.html#footer).

For a logo gallery on a single page, we can use the [cards](https://sphinx-design.readthedocs.io/en/latest/cards.html) from sphinx-design.
