### ISSUE TITLE
healpix should be healpy on page /hifs.html

### ISSUE THREAD

**Issue by Lucalino** [orcestra-campaign/book#462]
There seems to be a typo in the code cell loading python packages.

**Comment by lkluft** [comment]
Hi Luca,
We have [replaced `healpy` with `healpix`](https://github.com/orcestra-campaign/book/pull/390) in all our code. The `healpix` package comes with less overhead (other external dependencies and imports) and is also installable by Windows users.

In most cases, `healpix` works as a drop-in replacement, meaning you can simply change the import and leave your code as is.
