### ISSUE TITLE
Time zone definition on flight plans

### ISSUE THREAD

**Issue by heikekonow** [orcestra-campaign/book#76]
Looking at Flight plan - HALO-20240811a, some thoughts:
- it might be good to state the time format somewhere on the plan. (LT or UTC)
- in the past, I think we usually used LT (local time) for the plans and discussions everywhere (and FX did the conversion to UTC on their end). This might avoid confusion as everyone is living in local time anyway and as local time and UTC are very close together on Cap Verde (so it isn’t immediately obvious which time zone it is from just looking at the numbers).

I guess my main point is, that the time zone needs to be stated on the plan. 😇

**Comment by lkluft** [comment]
I agree that local time seems easier for planning. If we add additional metadata (e.g. `location` or `timezone`), we can also do the conversion on our end and simply print both times. This would also allow users (or scripts) to select flights based on the location.

I am not sure if there are any pitfalls in this approach, so I would appreciate any input from the experienced campaigners ☺️

**Comment by lkluft** [comment]
I opened a draft PR (#98) which we can use as a base for discussion
